GET http://localhost:3000/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiU3VyYWoiLCJpYXQiOjE2OTM2NDIwNjUsImV4cCI6MTY5MzY0MjA4MH0.YFq3nFO4X4F916kWpTr0w2lGEsKo8DZN6_KjLxbDOI4

###
POST http://localhost:4000/token
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiU3VyYWoiLCJpYXQiOjE2OTM2NDIyNDZ9.dnvoRwzd2cTvkfNTaUIVwxxg4mgEADxY99NGsCFRdS8"
}
###

DELETE http://localhost:4000/logout
Content-Type: application/json

{
    "token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiU3VyYWoiLCJpYXQiOjE2OTM2NDIyNDZ9.dnvoRwzd2cTvkfNTaUIVwxxg4mgEADxY99NGsCFRdS8"
}

###
POST http://localhost:4000/login
Content-Type: application/json

{
    "username": "Suraj"
}